# Implementation of TF-IDF Vectorizer


## TF-IDF Vectorizer

### Key idea
TF-IDF combines two signals:

- **Term Frequency (TF)**: how often a term appears in a document
- **Inverse Document Frequency (IDF)**: how rare the term is across all documents

### Formula
$$
\mathrm{TF-IDF}(t, d) = \mathrm{TF}(t, d) \times \mathrm{IDF}(t)
$$

$$
\mathrm{TF}(t, d) = \frac{\text{count of term } t \text{ in document } d}{\text{total terms in document } d}
$$

$$
\mathrm{IDF}(t) = \log\left(\frac{N}{\mathrm{DF}(t)}\right)
$$

Where:
- $N$ = total number of documents
- $\mathrm{DF}(t)$ = number of documents containing term $t$

### Implementation steps
1. Tokenize each document
2. Create the vocabulary
3. Compute TF for every term in every document
4. Compute IDF for every term
5. Multiply TF and IDF to get the final TF-IDF matrix

### Notes
- Terms that appear in many documents receive lower weights
- Terms that are frequent in a specific document but rare overall receive higher weights
- The final matrix is usually sparse, so efficiency matters for larger datasets

In [1]:
# input: documents = list[str]
documents = ["hello world","hello dog","bye bye cat"]

In [2]:
#tokenize each document
tokenized = [d.split() for d in documents]
tokenized

[['hello', 'world'], ['hello', 'dog'], ['bye', 'bye', 'cat']]

In [3]:
#create vocabulary using set to remove redundant words
vocab = sorted(set(word for words in tokenized for word in words)) #comprehension for two iterations
vocab

['bye', 'cat', 'dog', 'hello', 'world']

In [4]:
#creating a tf idf matrix of shape (no. of documents, no. of words in vocab)
# which in this case would be (3,5) matrix.
import numpy as np
tf_idf_mat = np.zeros((len(documents),len(vocab)))
tf_idf_mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#calculating tf_idf and updating tf_idf matrix
from collections import Counter
import math
for i,tokens in enumerate(tokenized):
    cnt = Counter(tokens)
    for j,word in enumerate(vocab):
        tf = cnt[word] / len(tokens)
        df = sum(1 for doc in tokenized if word in doc)
        idf = math.log(len(documents)/df) if df else 0
        tf_idf_mat[i][j] = tf*idf

tf_idf_mat,vocab


(array([[0.        , 0.        , 0.        , 0.20273255, 0.54930614],
        [0.        , 0.        , 0.54930614, 0.20273255, 0.        ],
        [0.73240819, 0.3662041 , 0.        , 0.        , 0.        ]]),
 ['bye', 'cat', 'dog', 'hello', 'world'])

### Functional Implementation

In [6]:
def tf_idf_vectorizer(documents):
    '''
    Args: 
        documents: list[str]
    Returns:
        Vocabulary and tf-idf matrix
    '''
    tokenized = [d.split() for d in documents]
    vocab = sorted(set(word for words in tokenized for word in words))

    tf_idf_mat = np.zeros((len(documents),len(vocab)))
    for i,tokens in enumerate(tokenized):
        cnt = Counter(tokens)
        for j,word in enumerate(vocab):
            tf = cnt[word] / len(tokens)
            df = sum(1 for doc in tokenized if word in doc)
            idf = math.log(len(documents)/df) if df else 0
            tf_idf_mat[i][j] = tf * idf
    
    return (vocab,tf_idf_mat)

tf_idf_vectorizer(documents)


(['bye', 'cat', 'dog', 'hello', 'world'],
 array([[0.        , 0.        , 0.        , 0.20273255, 0.54930614],
        [0.        , 0.        , 0.54930614, 0.20273255, 0.        ],
        [0.73240819, 0.3662041 , 0.        , 0.        , 0.        ]]))